---
title: "Paraguay: Estimation of the Impact of Transfer programs "
subtitle: "Pytyvo and Ñangareko (2019-2020)"
author: "Fernando Rios-Avila"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    ratio: 16:10
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{css, echo = FALSE}
.small   { /*Change made here*/
  font-size: 80% !important;
}
```
 
## Introduction

The goal of this presentation is to provide preliminary estimations exploring the targeting success of two transfer programs implemented in Paraguay.

This are the Pytyvo and Ñangareko.

Because these two programs were aiming to help people who have lost their main source of income, we will use the panel component from the Household Surveys in Paraguay. The idea is to explore if those who should have received this transfer indeed do so.


---
class: left

## Data 

We will concentrate on population age 17-69 in 2019. This will keep the comparison samples homogeneous in terms of age structure.

General Structure of data:


| Survay Year | Obs| Linked Obs | Tr Pytyvo | Tr Ñangareko|
|------:|---:|---:|---:|
| 2019 | 11473| 4293 |  1144 |  179 |
| 2020 | 11099| 4293 | 1144 |  179 |

Because these two transfers were similar. We will analyze them simultaneously.

---

## Model

To analyze if the transfers targeting was implemented correctly we would like to have information on Labor and Income Status after Covid but before transfers were implemented.

$$2019 \rightarrow covid  \rightarrow DATA!  \rightarrow transfers  \rightarrow 2020$$
Unfortunately, we only have data for either 2019 or 2020. 

The assumption: If transferences were temporary, what we observe in 2020 may be as close to the situation before transfers took place.

Thus, we will use that data to see, after the fact, if those who should have received the transfer indeed do so.

Caveat. If a group recovered from the **Covid** shock faster others (men vs women), we may not be able to measure this relationship.

---

# Results

Share of people who received the transfer by Transition and gender

|          | NE`->`E | NE`->`NE | E`->`E  | E`->`NE | Total |
| -------- | ----- | ------ | ----- | ----- | ----- |
| sexo     |       |        |       |       |       |
|   Hombre | 0.282 | 0.108  | 0.282 | 0.239 | 0.262 |
|   Mujer  | 0.365 | 0.227  | 0.275 | 0.401 | 0.285 |
|   Total  | 0.337 | 0.200  | 0.280 | 0.350 | 0.274 |

Message: 
- Those who lost jobs (E->NE) have the largest rates of receiving the transfers. 
- However, there are many people who didn't lose their jobs and yet received the transfer 

---

# Results

By formal employment

|          | Not Employed       | Informal | Formal   | Total    |
| -------- | -------- | -------- | -------- | -------- |
| sexo     |          |          |          |          |
|   Hombre | .169 | .357 | .094 | .262 |
|   Mujer  | .260 | .383  | .095 | .285 |
|   Total  | .237 | .368 | .095 | .274 |

Transfer were concentrated mostly on ppl with informal jobs in 2019. Especially among women. 
 

---

# Results
Here we show by change in income distribution. (Monthly income per capita)
`<-2q` means they moved 2 positions in the quintiles. Say from q3 to q1.

|          | <- 2q | <- 1q | no change | 1q -> | 2q -> | Total |
| -------- | ----- | ----- | --------- | ----- | ----- | ----- |
| sexo     |       |       |           |       |       |       |
|   Hombre | 0.313 | 0.306 | 0.234     | 0.261 | 0.306 | 0.262 |
|   Mujer  | 0.344 | 0.324 | 0.251     | 0.297 | 0.341 | 0.285 |
|   Total  | 0.328 | 0.315 | 0.243     | 0.279 | 0.325 | 0.274 |

Other than women showing higher rates of receiving the transfers, we see that regardless how much much income they may changed (moving up or down the distribution) there is not much change in the rate of receiving the transfer

---

# Results
However, conditioning only on those who were working in 2019 (and may be loosing their jobs), we see a larger share of ppl who received the transfer if they lost a lot of their income.

We see this more for women than men.

|          | <- 2q    | <- 1q    | no change | 1q ->    | 2q ->    | Total    |
| -------- | -------- | -------- | --------- | -------- | -------- | -------- |
| sexo     |       |       |           |       |       |       |
|   Hombre | 0.327 | 0.335 | 0.248     | 0.275 | 0.305 | 0.279 |
|   Mujer  | 0.445 | 0.335 | 0.262     | 0.312 | 0.335 | 0.302 |
|   Total  | 0.372 | 0.335 | 0.254     | 0.290 | 0.319 | 0.289 |



---

## Model

As a diagnostic for whether the transfer was well targeted, we will use a binomial model (logit) and explore to what extent the likelihood of receiving the transfer (trt=1) changes based on other characteristics:

$$ p(trt=1|X) = f(demo)+ f(J Stat, \Delta Emp, \Delta income) $$
We repeat this for the full sample, and for men and women separately.
 
>Controls: Urban/Rural, age, years of education, Head/Spouse vs other, is married.

---

#Results

| Marginal effects     |        Todos    |      Hombres    |      Mujeres    |
| -------------------- | :-------------: | :-------------: | :-------------: |
| NE->E                |       0.0557*   |      0.00708    |       0.0760**  |
|                      |     (0.0301)    |     (0.0496)    |     (0.0387)    |
| NE->NE               |      -0.0626*** |       -0.156*** |      -0.0385    |
|                      |     (0.0194)    |     (0.0302)    |     (0.0252)    |
| E->E                 |            0    |            0    |            0    |
|                      |          (.)    |          (.)    |          (.)    |
| E->NE                |       0.0736**  |      -0.0329    |        0.119*** |
|                      |     (0.0287)    |     (0.0456)    |     (0.0367)    |

Among women, job looser received the transfer more often. However, that isnt the case for men. 

Those who remain unemployed are less likely to get the transfer. For men, Those who didnt loos their jobs are more likely to have received the bonus

---

## Results

On the other hand, people working in formal sector were far less likely to receive the transfers.


| Marginal effects     |      Todos    |      Hombres    |      Mujeres    |
| -------------------- | :-------------: | :-------------: | :-------------: |
| Informal             |            0    |            0    |            0    |
|                      |          (.)    |          (.)    |          (.)    |
| Formal               |       -0.286*** |       -0.282*** |       -0.293*** |
|                      |     (0.0174)    |     (0.0219)    |     (0.0288)    |

---

## Results

Looking at the changes in the distribution:

1. In all cases, relative declines or increases in income increase the changes of receiving this transfer,

2. Only when the changes were negative (Fall in income) were the estimations significant. 
.small[

| Marginal effectgs    |        Todos    |      Hombres    |      Mujeres    |
| -------------------- | :-------------: | :-------------: | :-------------: |
| <- 2q                |       0.0919*** |       0.0910**  |       0.0920**  |
|                      |     (0.0308)    |     (0.0431)    |     (0.0441)    |
| <- 1q                |       0.0650*** |       0.0673**  |       0.0626**  |
|                      |     (0.0209)    |     (0.0297)    |     (0.0293)    |
| no change            |            0    |            0    |            0    |
| 1q ->                |       0.0302    |       0.0222    |       0.0393    |
|                      |     (0.0210)    |     (0.0292)    |     (0.0302)    |
| 2q ->                |       0.0727*   |       0.0780    |       0.0645    |
|                      |     (0.0373)    |     (0.0521)    |     (0.0526)    |

]

---

## Results

However, if we condition of having a job in 2019, we observe that only those whose income declined were reciving the transfer.

.small[

| Marginal effectgs    |        Todos    |      Hombres    |      Mujeres    |
| -------------------- | :-------------: | :-------------: | :-------------: |
| <- 2q                |        0.114*** |       0.0858*   |        0.168*** |
|                      |     (0.0365)    |     (0.0456)    |     (0.0598)    |
| <- 1q                |       0.0652*** |       0.0749**  |       0.0517    |
|                      |     (0.0246)    |     (0.0329)    |     (0.0371)    |
| no change            |            0    |            0    |            0    |
| 1q ->                |       0.0221    |       0.0176    |       0.0299    |
|                      |     (0.0257)    |     (0.0331)    |     (0.0401)    |
| 2q ->                |       0.0392    |       0.0680    |     -0.00367    |
|                      |     (0.0454)    |     (0.0595)    |     (0.0696)    |


]

---

# Conclusion

The evidence suggests that the transfers well reasonably well targeted. Specially for women who experience a loss of income and job.

However, some results suggests not everybody who received the transfer qualified for it. 
> Formal workers and those who didnt loose their jobs.

Caveats:
1. Men Labor market conditions improved faster than for women, which may explain part of the results.
2. We do not have information right before or after the Transfer was provided. Using a 2019 and 2020 as proxies may create a bias.
